loadType: sequence
features:
  - name: registrar-cashback
    feature: classpath:cl/bci/ecodig/acceptance/registrar-transaccion.feature@name=registrar-cashback
    performance: false
    reason: "Ejecucion Batch"
    reason_detail: "se ejecuta por topico service bus"
    concurrency: high
    iterations: low
    response_time: low
    operation_id: registrarTransaccion
  - name: registrar-bono-independiente
    feature: classpath:cl/bci/ecodig/acceptance/registrar-bono-independiente.feature@name=registrar-bono-independiente
    performance: false
    reason: "Transaccional"
    reason_detail: "Almacena datos en db"
    concurrency: high
    iterations: low
    response_time: low
    operation_id: registrarBonoIndependiente
  - name: inyeccion-transaccion
    feature: classpath:cl/bci/ecodig/acceptance/reinyectar-transacciones.feature@name=inyeccion-transaccion
    performance: true
    reason: ""
    reason_detail: ""
    concurrency: low
    iterations: low
    response_time: low
    operation_id: inyectarTransaccion
  - name: transaccion-pendiente
    feature: classpath:cl/bci/ecodig/acceptance/transaccion-pendiente.feature@name=transaccion-pendiente
    performance: false
    reason: "Ejecucion Batch"
    reason_detail: "endpoint ejecutado por cron una vez al dia"
    concurrency: high
    iterations: low
    response_time: low
    operation_id: procesarTransaccionesPendientes
  - name: listado-transacciones
    feature: classpath:cl/bci/ecodig/acceptance/listado-transacciones.feature@name=listado-transacciones
    performance: true
    reason: ""
    reason_detail: ""
    concurrency: very_low
    iterations: low
    response_time: low
    operation_id: obtenerListadoTransacciones
  - name: detalle-transaccion
    feature: classpath:cl/bci/ecodig/acceptance/detalle-transaccion.feature@name=detalle-transaccion
    performance: true
    reason: ""
    reason_detail: ""
    concurrency: very_low
    iterations: low
    response_time: low
    operation_id: obtenerDetalleTransaccion
  - name: cambiar-estado-cashback
    feature: classpath:cl/bci/ecodig/acceptance/cambiar-estado-transaccion.feature@name=cambiar-estado-cashback
    performance: true
    reason: ""
    reason_detail: ""
    concurrency: very_low
    iterations: low
    response_time: low
    operation_id: cambiarEstadoTransaccion