loadType: sequence
features:
  - name: Solicitud cesiones deudor
    feature: classpath:cl/bci/ecodig/acceptance/solicitud-cesiones-deudor.feature@name=SolicitudCesionesDeudor
    performance: true
    reason: "Se requiere performance"
    reason_detail: "Endpoint para solicitur cesiones de un deudor"
    concurrency: low
    iterations: low
    response_time: medium
    operation_id: obtenerRegistroCesionesPorDeudor
  - name: Obtener estado de tarea
    feature: classpath:cl/bci/ecodig/acceptance/obtener-estado-tarea.feature@name=ObtenerEstadoTarea
    performance: true
    reason: "Se requiere performance"
    reason_detail: "Endpoint para consultar estado de tarea"
    concurrency: low
    iterations: low
    response_time: medium
    operation_id: obtenerEstadoTareaCesiones
  - name: Obtener resultado de tarea
    feature: classpath:cl/bci/ecodig/acceptance/obtener-resultado-tarea.feature@name=ObtenerResultadoTarea
    performance: true
    reason: "Se requiere performance"
    reason_detail: "Endpoint para recuperar resultado de tarea"
    concurrency: low
    iterations: low
    response_time: medium
    operation_id: obtenerResultadoTareaCesiones